### ISSUE TITLE
Discuss: When should we show the Confirm Delete Dialog

### ISSUE THREAD

**Issue by eneufeld** [eclipsesource/jsonforms-editor#35]
The Confirm Delete Dialog only pops up when we delete a layout with children.

The user will be able to modify the UISchema.
I suggest to change the behavior to show the confirm dialog every time we delete a non empty layout. Otherwise the user could loose a configured control.
If we introduce an undo action we can get rid of the dialog.

@sdirix @AlexandraBuzila what is your take on this?

**Comment by sdirix** [comment]
In general I dislike such confirm/yes-no modals and would try to avoid them whenever possible. Once we have the undo/redo-workflow we should definitely get rid of them. For now only showing them when we delete a non-empty layout seems like a sensible compromise to me.

**Comment by eneufeld** [comment]
We keep the current state, which is like what Stefan described
