### ISSUE TITLE
Improve drag and drop vizualitation

### ISSUE THREAD

**Issue by koegel** [eclipsesource/jsonforms-editor#73]
**Motivation**
Help users to better understand where elements can be dropped to in the UI Schema and avoid that view is cluttered with drop targets all the time. 

**Solution**
This is just some ideas, needs some thought and experiments I guess:
1. Only show drop target zones on drag maybe even only when coming close. 
2. Make drop target zones larger and more "zone-like", e.g. rectangular with dotes lines. Potentially even previewing the potential size of the dropped element. Or even more advanced, previewing the layout to be when the element is dropped (seem difficult to me but surprise me :) )

**Comment by AlexandraBuzila** [comment]
Reopening to implement the visible on hover behavior for drop points.
